services:
  - type: web
    name: contract-iq-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    region: oregon
    branch: main
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY_FALLBACK
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: CORS_ORIGINS
        value: "https://contract-iq-light.vercel.app,https://*.vercel.app,http://localhost:3000"
      - key: DEBUG
        value: "false"